# Generated by Django 3.1.7 on 2021-03-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2014-12-12'),
            preserve_default=False,
        ),
    ]
