# Generated by Django 3.1.7 on 2021-03-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=250)),
                ('pic', models.ImageField(upload_to='pics')),
                ('details', models.TextField()),
            ],
        ),
    ]
